<a href="https://colab.research.google.com/github/Ecaballero333/Obligatorio_EDA1/blob/master/Practico_1_ML_intro_a_Python.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Práctico 1: Introducción a Python

### Types

In [ ]:
type(23)

int

In [ ]:
type(1.1)

float

In [ ]:
type('c')

str

In [ ]:
type(True)

bool

### Operations

In [ ]:
# Operaciones básicas
10+1

11

In [ ]:
12*2

24

In [ ]:
10-6

4

In [ ]:
9/2

4.5

In [ ]:
# Resultado de la división descartando fracciones
9//2

4

In [ ]:
# Resto de la división
9%2

1

In [ ]:
# Potencia
2**3

8

In [ ]:
# Asginación
a= 12
a

12

In [ ]:
b, c = 2,3
b,c

(2, 3)

In [ ]:
# Evaluación
a==b

False

In [ ]:
a>b

True

In [ ]:
a<=c

False

In [ ]:
c!=b

True

### Input y Print

In [ ]:
print('Como te llamas?')

Como te llamas?


In [ ]:
nombre = input('Como te llamas?')

Como te llamas?


In [ ]:
print('Hola', nombre, '!')


Hola  !


In [ ]:
edad = int(input('Cual es tu edad?'))

Cual es tu edad?


ValueError: ignored

In [ ]:
print(nombre, ' tiene ', edad, ' años')


### Control Structures

In [ ]:
edad = 36

In [ ]:
# IF
if edad < 20:
    print('Bienvenido al curso joven superdotado')
elif edad >= 20 and edad <= 35:
    print('Bienvenido al curso humano')
else:
    print('\_(¤ v ¤)_/')

\_(¤ v ¤)_/


In [ ]:
# WHILE
numero = 0
while numero < 10:
    print(numero)
    numero += 1

0
1
2
3
4
5
6
7
8
9


### Lists

In [ ]:
# Crear lista
lista = [1, 2, 3]
lista

[1, 2, 3]

In [ ]:
type(list)

list

In [ ]:
# Agregar elementos a una lista
lista.append(4)
lista

[1, 2, 3, 4]

In [ ]:
# Lista vacía
lista2 = []
lista2

[]

In [ ]:
# Elementos en cada lista
len(lista), len(lista2)

(4, 0)

In [ ]:
# Listas con diferentes tipos de datos
lista.append('hola')
lista

[1, 2, 3, 4, 'hola']

In [ ]:
lista+=[True,2.3]
lista

[1, 2, 3, 4, 'hola', True, 2.3]

In [ ]:
# Usar indices para acceder a los elementos de listas
lista[0]

1

In [ ]:
lista[-1]

2.3

In [ ]:
lista[-2]

True

In [ ]:
lista[1] + lista[2] == 6

False

In [ ]:
lista[1] + lista[2] == 5

True

In [ ]:
lista

[1, 2, 3, 4, 'hola', True, 2.3]

In [ ]:
# SLicing
lista[1:5]

[2, 3, 4, 'hola']

In [ ]:
lista[:5]

[1, 2, 3, 4, 'hola']

In [ ]:
lista[1:6:2]

[2, 4, True]

In [ ]:
lista[1:-2]

[2, 3, 4, 'hola']

In [ ]:
#  Recorrido de una lista
lista_rec = [0.0, 0.2, 0.3, 0.5, 0.6]
for i in lista_rec:
    print(i)


0.0
0.2
0.3
0.5
0.6


In [ ]:
# Recorrido en un rango
for i in range(0,len(lista_rec)):
    print(i)

0
1
2
3
4


### Dictionary

In [ ]:
diccionario = {}
type(diccionario)

dict

In [ ]:
keyValue = dict()
type(keyValue)

dict

In [ ]:
keyValue["test"] =  2

In [ ]:
keyValue

{'test': 2}

In [ ]:
keyValue["test"]

2

In [ ]:
keyValue = {'alumno1': 172121, 'alumno2': 412312, 'alumno5': 939121}

In [ ]:
keyValue.get('alumno5')

939121

In [ ]:
# Obtener los valores de un diccionario:
for value in keyValue.values():
  print(value)


172121
412312
939121


### Array

In [ ]:
import numpy as np

In [ ]:
np.array([1.5, 3, 4])

array([1.5, 3. , 4. ])

In [ ]:
np.array([0.5, 0.7, 0.2, 1.5], dtype=np.int32)

#pasa los numeros a enteros

array([0, 0, 0, 1], dtype=int32)

In [ ]:
a1 = np.array([1.5, 3, 4], dtype=np.int32)
a1

array([1, 3, 4], dtype=int32)

In [ ]:
np.sum(a1)

8

In [ ]:
np.mean(a1)

2.6666666666666665

In [ ]:
np.shape(a1)

(3,)

In [ ]:
a1.reshape(3, -1)

array([[1],
       [3],
       [4]], dtype=int32)

In [ ]:
np1 = np.ones(10)
np1
# genera un array de unos

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [ ]:
np.ones(10) * 3

array([3., 3., 3., 3., 3., 3., 3., 3., 3., 3.])

In [ ]:
np.zeros(10) + 1

# genera un array de ceros y les suma 1

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

### Matrices

In [ ]:
m1 = np.array([[1,2,3],[6,4,5]])
m1

array([[1, 2, 3],
       [6, 4, 5]])

In [ ]:
m1.shape

(2, 3)

In [ ]:
m1.reshape(3, -1)

array([[1, 2],
       [3, 6],
       [4, 5]])

In [ ]:
m1.transpose()

array([[1, 6],
       [2, 4],
       [3, 5]])

In [ ]:
np.sum(m1)
# suma todos los elementos de la matriz

21

In [ ]:
np.sum(m1, axis=0)

array([7, 6, 8])

In [ ]:
np.sum(m1, axis=1)

array([ 6, 15])

### Tuples

In [ ]:
t = (2, 3)
t

(2, 3)

In [ ]:
t[0]

2

In [ ]:
t[0:2]

(2, 3)

### Funciones

In [ ]:
def sum_two_numbers(a, b):
    return a + b

In [ ]:
sum_two_numbers(35656,74812)  

110468

### Classes

In [ ]:
# Creación clase Person
class Person:
    pass      

In [ ]:
ana=Person()

In [ ]:
type(ana)

__main__.Person

In [ ]:
class Person:
    
    def __init__(self, name, age):
        self.name = name
        self.age = age    

In [ ]:
maria = Person("Maria", 32)

In [ ]:
maria.age

32

In [ ]:
class Person:
    
    def __init__(self, name, age):
        self.name = name
        self.age = age
        
    def hi(self):
        print('¡Hola, ', self.name,'!')   

In [ ]:
juan = Person("Juan", 21)

In [ ]:
juan.hi()

¡Hola,  Juan !


### Random

In [ ]:
np.random.seed(2)

In [ ]:
np.random.random()

0.43599490214200376

In [ ]:
np.random.random(10)

array([0.02592623, 0.54966248, 0.43532239, 0.4203678 , 0.33033482,
       0.20464863, 0.61927097, 0.29965467, 0.26682728, 0.62113383])

In [ ]:
np.random.normal(0, 20, 2)

array([-22.21455512,   1.77160134])

## Ejercicios

In [ ]:
# Usando un loop crear una lista con los números enteros entre 0 y 100 (tip: usar range())
list = []
for i in range(0,101):
    list.append(i)

In [ ]:
# Crear una lista con la cantidad de ceros que uno desee:
def zerolistmaker(n):
    listofzeros = [0] * n
    return listofzeros


In [ ]:
lista_ceros = zerolistmaker(7)
lista_ceros

[0, 0, 0, 0, 0, 0, 0]

In [ ]:
# Seleccionar los elementos 20 a 30
list[19:30]

[19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29]

In [ ]:
# Seleccionar de la lista solo los elementos multiplos de 10
list[::10]

[0, 10, 20, 30, 40, 50, 60, 70, 80, 90, 100]

In [ ]:
# Seleccionar los últimos 5 elementos de la lista
list[-5:]

[96, 97, 98, 99, 100]

In [ ]:
# Crear una función que devuelva la diferencia entre el número mayor y el menor, ejemplo dif(2,5)=3 y dif(5,2)=3
def dif(a,b):
  if(a > b):
    result = a-b
  else:
    result = b-a
  return result

In [ ]:
# Subir un archivo local a Google Colab

# Tambien podemos subir archivos directamente desde un repositorio (primero deberemos hacer un "clone" del mismo)

from google.colab import files 
  
  
uploaded = files.upload()

In [ ]:
# Levantar un archivo csv

import pandas as pd

consumo = pd.read_csv('consumo.csv', sep=',')
consumo

fecha  consumo_miles_m3
0    2010/01            68.874
1    2010/02            60.128
2    2010/03            84.494
3    2010/04            79.147
4    2010/05            72.691
..       ...               ...
127  2020/08            70.691
128  2020/09            73.769
129  2020/10            81.305
130  2020/11            85.335
131  2020/12            79.887

[132 rows x 2 columns]

In [ ]:
# Tambien podemos declarar un Data Frame vacio:
consumo_vacio = pd.DataFrame(columns=('Fecha', 'consumo_miles_m3'))
consumo_vacio

Empty DataFrame
Columns: [Fecha, consumo_miles_m3]
Index: []

In [ ]:
type(consumo)

pandas.core.frame.DataFrame

In [ ]:
# Visualizar columnas de un dataframe
df_aux = consumo
df_aux.columns

Index(['fecha', 'consumo_miles_m3'], dtype='object')

In [ ]:
# Renombrar columnas de un dataframe
df_aux.columns = ['Fecha', 'consumo_gasoil']
df_aux.columns

Index(['Fecha', 'consumo_gasoil'], dtype='object')

In [ ]:
# Seleccionamos valor de una fila/ columna
df_aux.iloc[1]['Fecha']

'2010/02'

In [ ]:
df_aux.iloc[0]['consumo_gasoil']

68.874

In [ ]:
# Eliminar columnas de un dataframe:
df_aux_cortado = df_aux.drop(columns=['Fecha'])
df_aux_cortado

consumo_gasoil
0            68.874
1            60.128
2            84.494
3            79.147
4            72.691
..              ...
127          70.691
128          73.769
129          81.305
130          85.335
131          79.887

[132 rows x 1 columns]

In [ ]:
# Agregado de una columna a un dataframe:

df_aux_cortado['Fecha']= consumo['Fecha']
df_aux_cortado

consumo_gasoil    Fecha
0            68.874  2010/01
1            60.128  2010/02
2            84.494  2010/03
3            79.147  2010/04
4            72.691  2010/05
..              ...      ...
127          70.691  2020/08
128          73.769  2020/09
129          81.305  2020/10
130          85.335  2020/11
131          79.887  2020/12

[132 rows x 2 columns]

In [ ]:
# Eliminar filas por indice de un dataframe
df_aux_cortado = df_aux_cortado.drop([131], axis = 0)
df_aux_cortado

consumo_gasoil    Fecha
0            68.874  2010/01
1            60.128  2010/02
2            84.494  2010/03
3            79.147  2010/04
4            72.691  2010/05
..              ...      ...
126          72.149  2020/07
127          70.691  2020/08
128          73.769  2020/09
129          81.305  2020/10
130          85.335  2020/11

[131 rows x 2 columns]

In [ ]:
# Recorrer un data frame
# Pasamos los elementos de la columna "consumo_gasoil" a una lista
l_aux = []
for i in range(0,len(df_aux_cortado)):
  l_aux.append(df_aux_cortado.iloc[i]['consumo_gasoil'])
l_aux

[68.874,
 60.128,
 84.494,
 79.14699999999999,
 72.691,
 69.217,
 66.817,
 71.637,
 70.391,
 83.131,
 78.393,
 83.81,
 62.861000000000004,
 68.118,
 79.468,
 81.208,
 80.52,
 69.411,
 65.623,
 69.487,
 79.105,
 72.27600000000001,
 90.184,
 82.524,
 65.557,
 68.499,
 76.23,
 79.642,
 81.502,
 69.39699999999999,
 69.828,
 63.321000000000005,
 70.775,
 70.809,
 91.948,
 68.126,
 66.421,
 60.778,
 72.404,
 89.36,
 77.861,
 75.23899999999999,
 68.96600000000001,
 74.988,
 62.599,
 84.244,
 75.171,
 86.15299999999999,
 59.339,
 57.193999999999996,
 72.207,
 89.31,
 76.066,
 73.352,
 69.027,
 73.314,
 73.187,
 78.393,
 77.61399999999999,
 76.118,
 63.525,
 66.11399999999999,
 81.84,
 94.411,
 72.21600000000001,
 73.396,
 69.015,
 54.216,
 68.598,
 75.792,
 77.12100000000001,
 73.694,
 58.508,
 64.067,
 71.292,
 63.507,
 92.671,
 75.593,
 60.075,
 75.48899999999999,
 72.919,
 72.078,
 87.139,
 83.367,
 57.049,
 61.48,
 85.29799999999999,
 79.316,
 76.51,
 78.722,
 65.008,
 67.392,
 67.824,
 82

In [ ]:
# Convertir una lista en un dataframe:
lista = [1, 2, 3]

df_list= pd.DataFrame(lista)
df_list

0
0  1
1  2
2  3

In [ ]:
# Subiremos un nuevo dataframe:

uploaded = files.upload()

Saving dias_venta_teoricos.csv to dias_venta_teoricos.csv


In [ ]:
dv = pd.read_csv('dias_venta_teoricos.csv', sep=',')
dv

Dias de Venta
0               23
1               20
2               21
3               22
4               23
..             ...
127             23
128             20
129             23
130             22
131             21

[132 rows x 1 columns]

In [ ]:
# Concatenado de dataframes:

df_total = pd.concat([df_aux, dv], axis = 1)
df_total

Fecha  consumo_gasoil  Dias de Venta
0    2010/01          68.874             23
1    2010/02          60.128             20
2    2010/03          84.494             21
3    2010/04          79.147             22
4    2010/05          72.691             23
..       ...             ...            ...
127  2020/08          70.691             23
128  2020/09          73.769             20
129  2020/10          81.305             23
130  2020/11          85.335             22
131  2020/12          79.887             21

[132 rows x 3 columns]

In [ ]:
# TRATAMIENTO DE UN DATAFRAME CON FILAS DUPLICADAS:

In [ ]:
uploaded = files.upload()

NameError: ignored

In [ ]:
df_repetidas = pd.read_csv('df_filas_duplicadas.csv', sep=',')
df_repetidas

Datos
0       20
1       21
2       22
3       23
4       20
..     ...
118     23
119     20
120     23
121     22
122     21

[123 rows x 1 columns]

In [ ]:
# Ver filas duplicadas en un dataframe
# En este ejemplo, a partir de la cuarta fila en adelante, todas las filas estan duplicadas
df_repetidas.duplicated()

0      False
1      False
2      False
3      False
4       True
       ...  
118     True
119     True
120     True
121     True
122     True
Length: 123, dtype: bool

In [ ]:
# Nos quedamos solo con las filas duplicadas: O sea de la cuarta en adelante:

duplicate = df_repetidas[df_repetidas.duplicated()]
duplicate

Datos
4       20
5       23
6       22
7       21
8       21
..     ...
118     23
119     20
120     23
121     22
122     21

[119 rows x 1 columns]

In [ ]:
# Vemos cuantas filas son:
len(duplicate)

119

In [ ]:
# Funcion que elimina las filas duplicadas
res = df_repetidas.drop_duplicates() 
res 

Datos
0     20
1     21
2     22
3     23

In [ ]:
# Funcion para eliminar filas duplicadas en un dataframe:

def clean_duplicate(df,duplicate=True):
    if duplicate is True:
        duplicate = df[df.duplicated()]
        print("Número de filas duplicadas:", len(duplicate))
        res = df.drop_duplicates() 
    else: res=df   
    return res

In [ ]:
df_arreglado = clean_duplicate(df_repetidas,True)
df_arreglado

Número de filas duplicadas: 119


Datos
0     20
1     21
2     22
3     23

In [ ]:
# TRATAMIENTO DE UN DATAFRAME CON FILAS EN BLANCO

In [ ]:
uploaded = files.upload()

NameError: ignored

In [ ]:
df_blanco = pd.read_csv('df_filas_blanco.csv', sep=',')
df_blanco

Datos
0      20
1      21
2      22
3      23
4      20
..    ...
118    22
119    21
120    21
121    22
122    23

[123 rows x 1 columns]

In [ ]:
df_blanco.iloc[6]['Datos']

'_'

In [ ]:

def clean_duplicate(df,duplicate=True):
    if duplicate is True:
        duplicate = df[df.duplicated()]
        print("Número de filas duplicadas:", len(duplicate))
        res = df.drop_duplicates() 
    else: res=df   
    return res

In [ ]:
# Funcion para eliminar columnas duplicadas en un dataframe
def clean_blanks(df, blank_rows =True):
  if blank_rows is True:
      res = df
      for i in df:
        blank_rows = df[ (df[i] == '\n') | (df[i] == '') | (df[i] == None) | (res[i] == '_')] .index 
        print("Número de filas en blanco:", len(blank_rows))
        res=res.drop(res[ (res[i] == '\n') | (res[i] == '') | (res[i] == None) | (res[i] == '_')] .index, axis = 0)
  else: res=df
  return res

In [ ]:
df_arreglado_blanco = clean_blanks(df_blanco, True)
df_arreglado_blanco

Número de filas en blanco: 10


Datos
0      20
1      21
2      22
3      23
4      20
..    ...
118    22
119    21
120    21
121    22
122    23

[113 rows x 1 columns]

In [ ]:
df_arreglado_blanco.iloc[6]['Datos']

'21'

In [ ]:
# AMBAS FUNCIONES EN FORMA CONJUNTA:

In [ ]:
def clean(df,duplicate=True,blank_rows =True):
    if duplicate is True:
        duplicate = df[df.duplicated()]
        print("Número de filas duplicadas:", len(duplicate))
        res = df.drop_duplicates() 
    else: res=df    
    if blank_rows is True:
        for i in df:
            blank_rows = df[ (df[i] == '\n') | (df[i] == '') | (df[i] == None) | (df[i] == '_')] .index 
        print("Número de filas en blanco:", len(blank_rows))
        res=res.drop(res[ (res[i] == '\n') | (res[i] == '') | (res[i] == None)| (df[i] == '_')] .index, axis = 0)
    else: res=df
    return res

In [ ]:
df_arreglado_total = clean_duplicate(df_blanco, True)
df_arreglado_total

Número de filas duplicadas: 118


Datos
0    20
1    21
2    22
3    23
6     _

In [ ]:
df_arreglado_total = clean(df_blanco, True, True)
df_arreglado_total

Número de filas duplicadas: 118
Número de filas en blanco: 10


/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:11: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  # This is added back by InteractiveShellApp.init_path()


Datos
0    20
1    21
2    22
3    23

In [ ]:

# Consideraciones al trabajar con dataframes
# En general, eliminamos las filas duplicadas, a menos que aporten informacion. Si hay elementos faltantes (datos en null, quizas podemos completarlos con el promedio del total de datos, dependiendo de si tiene sentido o no)
# Eliminar filas que estan en blanco, o que tienen datos clave en null (al eliminar un dato en null, estamos eliminando los datos correspondientes a otras columnas/variables de la misma fila)

In [ ]:
# ESCALADO DE LOS DATOS: Muy util en redes neuronales

from sklearn.preprocessing import MinMaxScaler

scaler_datos = MinMaxScaler(feature_range = (0, 1)).fit(dv)
dv = scaler_datos.transform(dv)
dv

array([[1.        ],
       [0.        ],
       [0.33333333],
       [0.66666667],
       [1.        ],
       [0.        ],
       [1.        ],
       [0.66666667],
       [0.33333333],
       [1.        ],
       [0.33333333],
       [0.66666667],
       [1.        ],
       [0.        ],
       [0.33333333],
       [0.66666667],
       [0.66666667],
       [0.33333333],
       [1.        ],
       [0.33333333],
       [0.66666667],
       [1.        ],
       [0.        ],
       [1.        ],
       [0.66666667],
       [0.        ],
       [1.        ],
       [0.66666667],
       [0.33333333],
       [0.66666667],
       [0.66666667],
       [0.66666667],
       [0.66666667],
       [0.33333333],
       [0.66666667],
       [1.        ],
       [0.33333333],
       [0.        ],
       [1.        ],
       [0.33333333],
       [0.66666667],
       [0.66666667],
       [0.33333333],
       [1.        ],
       [0.66666667],
       [0.33333333],
       [0.66666667],
       [0.666

In [ ]:
dv = scaler_datos.inverse_transform(dv)
dv

array([[23.],
       [20.],
       [21.],
       [22.],
       [23.],
       [20.],
       [23.],
       [22.],
       [21.],
       [23.],
       [21.],
       [22.],
       [23.],
       [20.],
       [21.],
       [22.],
       [22.],
       [21.],
       [23.],
       [21.],
       [22.],
       [23.],
       [20.],
       [23.],
       [22.],
       [20.],
       [23.],
       [22.],
       [21.],
       [22.],
       [22.],
       [22.],
       [22.],
       [21.],
       [22.],
       [23.],
       [21.],
       [20.],
       [23.],
       [21.],
       [22.],
       [22.],
       [21.],
       [23.],
       [22.],
       [21.],
       [22.],
       [22.],
       [22.],
       [20.],
       [23.],
       [20.],
       [23.],
       [22.],
       [21.],
       [23.],
       [21.],
       [22.],
       [22.],
       [21.],
       [23.],
       [20.],
       [22.],
       [21.],
       [23.],
       [21.],
       [22.],
       [23.],
       [20.],
       [23.],
       [22.],
      

In [ ]:
# Esta funcion genera una lista de diccionarios
def crearExperimentos(autos,camiones,motos,calidades):
    experimentos = []
    for auto in autos:
        for camion in camiones:
            for moto in motos:
                for calidad in calidades:
                    if (len(calidad[0]) > 0) and (len(calidad[1]) > 0):
                        nombre = "A_B"
                    elif (len(calidad[0]) > 0):
                        nombre = "A"
                    elif len(calidad[1]) > 0:
                        nombre = "B"
                    else:
                        nombre = "1_B"
                    e = {
                            "nombre":nombre,
                            "Auto": auto,
                            "Camion": camion,
                            "Moto": moto,
                            "Calidad":calidad
                        }
                    experimentos.append(e)
    return experimentos

In [ ]:
autos = ['mercedez','toyota','susuki','bmw']
camiones = ['camion1','camion2','camion3']
motos = ['moto1','moto2','moto3']
calidades = [(['buena'], []), (['mala'], []), (['buena'], ['mala'])]

experimentos = crearExperimentos(autos, camiones, motos, calidades)

experimentos


In [ ]:
# GENERACION DE ARCHIVOS EN MODO LOCAL

path_salida  = "C:\\Users\\usuario\\Desktop\\curso_ML_ORT\\"

contador = 0
for e in experimentos:
  archivoSalida = open ("{}\\informacion_vehiculos.txt{}".format(path_salida, contador), "w")
  
  contador +=1
  Auto = e["Auto"]
  Camion = e["Camion"]
  Moto = e["Moto"]
  Calidad_A = e["Calidad"][0]
  Calidad_B = e["Calidad"][1]
  
  archivoSalida.write("Calidades:\nCalidad A: {}\nCalidad B: {}\n\nAutos: {}\nCamiones: {}\nMotos: {}\n\n". \
                  format(e["Calidad"][0],e["Calidad"][1],e["Auto"],e["Camion"],e["Moto"]))
  archivoSalida.close()


In [ ]:
# https://www.anaconda.com/products/individual/get-started

In [ ]:
# CALENDARIO

In [ ]:
from datetime import date
from dateutil.relativedelta import relativedelta
from calendar import monthcalendar

In [ ]:
monthcalendar(2021,5) 


[[0, 0, 0, 0, 0, 1, 2],
 [3, 4, 5, 6, 7, 8, 9],
 [10, 11, 12, 13, 14, 15, 16],
 [17, 18, 19, 20, 21, 22, 23],
 [24, 25, 26, 27, 28, 29, 30],
 [31, 0, 0, 0, 0, 0, 0]]

Nos devuelve listas (cada lista es una semana del mes, y pone lunes en la posición cero, martes en la posición uno, y asi sucesivamente).El ejemplo es para mayo 2021:

En el ejemplo de mayo 2021, vemos que la primer lista tiene 1, 2 en las posiciones 6 y 7 de la semana, que corresponden a sabado y domingo. En la lista dos, tenemos lunes 3 en la posición 1, martes 4 en la posición 2, y asi sucesivamente.`

In [ ]:
[j for i in monthcalendar(2021, 5) for j in i[:5] if j != 0]

# Deja todo lo anterior (o sea solo los días hábiles del mes) en una sola lista.

[3, 4, 5, 6, 7, 10, 11, 12, 13, 14, 17, 18, 19, 20, 21, 24, 25, 26, 27, 28, 31]

In [ ]:
# TODO JUNTO:

def dias_habiles(anio, mes):
    return len([j for i in monthcalendar(anio, mes) for j in i[:5] if j != 0])

In [ ]:
cant_habiles = dias_habiles(2021,8)
cant_habiles

22

In [ ]:
# Obtener Fecha Actual
date.today() 

datetime.date(2021, 8, 17)

In [ ]:
# Podemos cambiar la fecha actual a otro momento del tiempo usando "replace"
date.today().replace(year = 2019).replace(month = 1)

datetime.date(2019, 1, 17)